name: Build multi platform Rust CLI
description: Runs build step for multiple platforms to generate Rust Build

inputs:
  runner_os:
    description: "Type of OS"
    required: true
  target_platform:
    description: "OS platform"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ inputs.target_platform }}
    - name: Build
      run: cargo build --release --target=${{ inputs.target_platform }}
      shell: bash
